# Generated by Django 5.2.4 on 2025-07-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0002_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoterequest",
            name="delivery_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Calculated delivery cost",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="delivery_distance_km",
            field=models.FloatField(
                blank=True, help_text="Calculated distance in km", null=True
            ),
        ),
    ]
