# Generated by Django 5.2.4 on 2025-07-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0003_quoterequest_delivery_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Price of the product",
                max_digits=8,
            ),
        ),
    ]
