# Generated by Django 5.2.4 on 2025-07-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0004_product_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quoterequest",
            old_name="price_estimate",
            new_name="estimated_cost",
        ),
        migrations.RemoveField(
            model_name="quoterequest",
            name="delivery_cost",
        ),
        migrations.RemoveField(
            model_name="quoterequest",
            name="delivery_distance_km",
        ),
        migrations.RemoveField(
            model_name="quoterequest",
            name="delivery_suburb",
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="calculator_type",
            field=models.CharField(
                choices=[
                    ("retaining_wall", "Retaining Wall"),
                    ("under_fence_plinth", "Under Fence Plinth"),
                ],
                default="retraining_wall",
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="delivery_address",
            field=models.CharField(default="TBD", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="fence_length",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="plinths_per_panel",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="sleeper_brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="sleeper_length",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="sleeper_style",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="sleeper_thickness",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="steel_post_height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="steel_posts_required",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="steel_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="total_panels",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="total_plinths",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="total_sleepers",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="wall_height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="wall_length",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
