# Generated by Django 5.2.4 on 2025-07-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0005_rename_price_estimate_quoterequest_estimated_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoterequest",
            name="delivery_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="delivery_postcode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
