# Generated by Django 5.2.4 on 2025-07-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0006_quoterequest_delivery_cost_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quoterequest",
            name="delivery_postcode",
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="delivery_zone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="delivery_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
