# Generated by Django 5.2.4 on 2025-07-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0007_remove_quoterequest_delivery_postcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoterequest",
            name="delivery_postcode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
