# Generated by Django 5.2.4 on 2025-07-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0008_quoterequest_delivery_postcode_quoterequest_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300)),
                ("answer", models.TextField()),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in which this FAQ appears"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
