# Generated by Django 5.2.4 on 2025-07-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0010_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoterequest",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
