# Generated by Django 5.2.4 on 2025-07-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0011_quoterequest_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quoterequest",
            name="phone",
            field=models.CharField(default="UNKNOWN", max_length=20),
            preserve_default=False,
        ),
    ]
