# Generated by Django 5.2.4 on 2025-07-25 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0012_alter_quoterequest_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("billing_address_line1", models.CharField(blank=True, max_length=255)),
                ("billing_address_line2", models.CharField(blank=True, max_length=255)),
                ("billing_city", models.CharField(blank=True, max_length=100)),
                ("billing_state", models.CharField(blank=True, max_length=100)),
                ("billing_postcode", models.CharField(blank=True, max_length=10)),
                (
                    "billing_country",
                    models.CharField(default="Australia", max_length=100),
                ),
                (
                    "delivery_address_line1",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "delivery_address_line2",
                    models.CharField(blank=True, max_length=255),
                ),
                ("delivery_city", models.CharField(blank=True, max_length=100)),
                ("delivery_state", models.CharField(blank=True, max_length=100)),
                ("delivery_postcode", models.CharField(blank=True, max_length=10)),
                (
                    "delivery_country",
                    models.CharField(default="Australia", max_length=100),
                ),
                ("delivery_zone", models.CharField(blank=True, max_length=50)),
                (
                    "delivery_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliverySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time_slot", models.CharField(max_length=50)),
                ("capacity", models.PositiveIntegerField(default=5)),
                ("is_available", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["date", "time_slot"],
                "unique_together": {("date", "time_slot")},
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "delivery_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=200),
                ),
                ("stripe_charge_id", models.CharField(blank=True, max_length=200)),
                ("payment_method", models.CharField(default="stripe", max_length=50)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("xero_invoice_id", models.CharField(blank=True, max_length=200)),
                ("xero_invoice_number", models.CharField(blank=True, max_length=100)),
                ("xero_synced_at", models.DateTimeField(blank=True, null=True)),
                ("delivery_notes", models.TextField(blank=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="quotes.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=50)),
                ("product_name", models.CharField(max_length=200)),
                ("product_length", models.CharField(blank=True, max_length=20)),
                ("product_thickness", models.CharField(blank=True, max_length=20)),
                ("product_style", models.CharField(blank=True, max_length=100)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField()),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="quotes.order",
                    ),
                ),
            ],
        ),
    ]
