# Generated by Django 5.2.4 on 2025-07-26 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0013_customer_deliveryslot_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryslot",
            name="created_by",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="deliveryslot",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("internal", "Internal Delivery"),
                    ("external", "External Partner"),
                    ("both", "Both Available"),
                ],
                default="both",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="deliveryslot",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Internal notes about this time slot"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quotes.deliveryslot",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "Delivery Pending"),
                    ("accepted", "Delivery Accepted"),
                    ("rejected", "Delivery Rejected"),
                    ("outsourced", "Passed to RB Transport"),
                    ("scheduled", "Delivery Scheduled"),
                    ("completed", "Delivery Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_time_slot",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_vehicle",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="internal_delivery_assigned_to",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="rb_transport_response",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="rb_transport_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="rb_transport_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
