# Generated by Django 5.2.4 on 2025-07-26 15:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0014_deliveryslot_created_by_deliveryslot_delivery_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountableProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        help_text="Product ID from products_data.py",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Product name", max_length=200)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Product category (e.g. Sleepers, Posts, UFP)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Discount code (e.g. SAVE20, WELCOME10)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name for this discount", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description shown to customers"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage Off"),
                            ("fixed_amount", "Fixed Amount Off"),
                            ("free_shipping", "Free Shipping"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (e.g. 20 for 20%) or fixed amount",
                        max_digits=10,
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Leave blank for unlimited uses",
                        null=True,
                    ),
                ),
                (
                    "max_uses_per_customer",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many times each customer can use this code",
                    ),
                ),
                (
                    "minimum_order_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum order total to use this code",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, help_text="Leave blank for no expiry", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applicable_products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty to apply to all products",
                        to="quotes.discountableproduct",
                    ),
                ),
                (
                    "exclude_products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Products to exclude from this discount",
                        related_name="excluded_from_discounts",
                        to="quotes.discountableproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiscountUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_email", models.EmailField(max_length=254)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "discount_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="quotes.discountcode",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quotes.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-used_at"],
            },
        ),
    ]
