# Generated by Django 5.2.4 on 2025-07-26 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0015_discountableproduct_discountcode_discountusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quotes.discountcode",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="applicable_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty to apply to all products",
                related_name="applicable_discounts",
                to="quotes.discountableproduct",
            ),
        ),
    ]
