# Generated by Django 5.2.4 on 2025-07-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0016_order_discount_amount_order_discount_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="General", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
