# Generated by Django 5.2.4 on 2025-07-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0017_product_category_product_color_product_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryslot",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("internal", "Internal Delivery"),
                    ("external", "External Partner"),
                    ("pickup", "Customer Pickup"),
                    ("both", "Both Available"),
                ],
                default="both",
                max_length=20,
            ),
        ),
    ]
