# Generated by Django 5.2.4 on 2025-08-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0018_alter_deliveryslot_delivery_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryslot",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("internal", "Internal Delivery"),
                    ("external", "External Partner"),
                    ("pickup", "Customer Pickup"),
                    ("Both Avaliable", "Both Available"),
                ],
                default="Both Avaliable",
                max_length=20,
            ),
        ),
    ]
