# Generated by Django 5.2.4 on 2025-08-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0019_alter_deliveryslot_delivery_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoterequest",
            name="custom_message",
            field=models.TextField(
                blank=True,
                help_text="Additional notes or requirements from customer",
                null=True,
            ),
        ),
    ]
