# Generated by Django 5.2.4 on 2025-08-02 10:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0020_quoterequest_custom_message"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="deliveryslot",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="deliveryslot",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 8, 2, 10, 27, 42, 678265, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deliveryslot",
            name="is_auto_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="deliveryslot",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("internal", "Internal Delivery"),
                    ("external", "External Partner"),
                    ("pickup", "Customer Pickup"),
                    ("Both Available", "Both Available"),
                ],
                default="Both Available",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="deliveryslot",
            unique_together={("date", "time_slot", "delivery_type")},
        ),
        migrations.CreateModel(
            name="DeliveryTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (e.g., 'Weekday Morning Deliveries')",
                        max_length=100,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("time_slot", models.CharField(max_length=50)),
                ("capacity", models.PositiveIntegerField(default=5)),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[
                            ("internal", "Internal Delivery"),
                            ("external", "External Partner"),
                            ("pickup", "Customer Pickup"),
                            ("Both Available", "Both Available"),
                        ],
                        default="Both Available",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Generate slots for this template"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "exclude_dates",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated dates to exclude (YYYY-MM-DD format). E.g., 2024-12-25,2024-01-01",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["day_of_week", "time_slot"],
                "unique_together": {("day_of_week", "time_slot", "delivery_type")},
            },
        ),
        migrations.AddField(
            model_name="deliveryslot",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template used to generate this slot (if auto-generated)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quotes.deliverytemplate",
            ),
        ),
    ]
