# Generated by Django 5.2.4 on 2025-08-02 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0021_alter_deliveryslot_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("full_name", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExcelSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=200)),
                ("file_path", models.CharField(max_length=500)),
                ("last_modified", models.DateTimeField()),
                ("sync_started", models.DateTimeField(auto_now_add=True)),
                ("sync_completed", models.DateTimeField(blank=True, null=True)),
                ("products_created", models.PositiveIntegerField(default=0)),
                ("products_updated", models.PositiveIntegerField(default=0)),
                ("errors", models.TextField(blank=True)),
                ("success", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("galvanised_steel", "Galvanised Steel"),
                            ("concrete_sleepers", "Concrete Sleepers"),
                            ("concrete_ufp_cribs", "Concrete UFPs and Cribs"),
                            ("step_kits", "Step Kits"),
                            ("accessories", "Accessories"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product_groups/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="quotes.productcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "sort_order", "name"],
                "unique_together": {("category", "name")},
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("length", models.CharField(blank=True, max_length=20)),
                ("height", models.CharField(blank=True, max_length=20)),
                ("thickness", models.CharField(blank=True, max_length=20)),
                ("width", models.CharField(blank=True, max_length=20)),
                ("is_rebated", models.BooleanField(default=False)),
                ("is_tapered", models.BooleanField(default=False)),
                ("smooth_finish", models.CharField(blank=True, max_length=20)),
                ("opening_size", models.CharField(blank=True, max_length=20)),
                ("price_ex_gst", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Weight in kg",
                        max_digits=8,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "excel_row_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference to Excel row for syncing",
                        max_length=50,
                    ),
                ),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="quotes.brand",
                    ),
                ),
                (
                    "product_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="quotes.productgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["product_group", "brand", "length", "height", "thickness"],
            },
        ),
    ]
