# Generated by Django 5.2.4 on 2025-08-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0022_brand_excelsynclog_productcategory_productgroup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="special_requests",
            field=models.TextField(
                blank=True,
                help_text="Customer special requirements like sleeper cutting, delivery instructions, etc.",
                max_length=1000,
                null=True,
                verbose_name="Special Requests",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
