# Generated by Django 5.2.4 on 2025-08-12 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0023_order_special_requests_alter_product_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountableproduct",
            name="mapped_product",
            field=models.ForeignKey(
                blank=True,
                help_text="Mapped to new Product model",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quotes.product",
            ),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="applicable_categories",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of categories to include (e.g. 'Steel,Sleepers')",
            ),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="exclude_categories",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of categories to exclude"
            ),
        ),
        migrations.AlterField(
            model_name="discountableproduct",
            name="category",
            field=models.CharField(
                blank=True, help_text="Product category", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="discountableproduct",
            name="product_id",
            field=models.CharField(
                help_text="LEGACY: Product ID from products_data.py",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="applicable_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty to apply to all products",
                related_name="applicable_discounts",
                to="quotes.product",
            ),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="exclude_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Products to exclude from this discount",
                related_name="excluded_from_discounts",
                to="quotes.product",
            ),
        ),
    ]
